[versions]
agp = "8.3.2"
kotlin = "2.0.0"
androidxCore = "1.13.1"
androidxJunit = "1.1.5"
junit = "4.13.2"
material3 = "1.2.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

